openapi: 3.0.1
info:
  title: Conten Manager System API
  description: 内容管理接口 API
  version: 2.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /shop/list:
    get:
      tags:
        - Shop Manager
      summary: 获取所有的店铺列表 前期可以不考虑分页
      parameters:
        - name: isForAppStore
          in: query
          required: false
          schema:
            type: boolean
          description:  isForAppStore 筛选是否是提供给 app store 审核的假数据，默认是 true
      responses:
        '200':
          description: 返回值商家
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                  data:
                    type: array
                    items:
                      items:
                        $ref: '#/components/schemas/ShopItem'
  /shop/create:
    post:
      tags:
        - Shop Manager
      summary: 创建一个新的商家 isForAppStore 这个是提供给 app-store 的假数据，如果填写 true 的话就会创建一些为 app store 审核的假数据。
      requestBody:
        $ref: '#/components/requestBodies/ShopCreateOrEditReq'
      responses:
        '200':
          description: 返回值商家
          content:
            application/json:
              schema:
                properties:
                  code:
                    type: integer
                    format: int32
                  data:
                    type: object
                    properties:
                      shopId:
                        type: integer
                        format: int64


components:
  schemas:
    ShopItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: 商家 ID
        name:
          type: string
          description: 商家名称

    ShopCreateModal:
      type: object
      properties:
        isForAppStore:
          type: boolean
          required: false
          default: false
          description: 这个是提供给 app-store 的假数据，如果填写 true 的话就会创建一些为 app store 审核的假数据。
        img:
          type: string
          description: 商家主图
        shopName:
          type: string
          description: 商家名称
        score:
          type: double
          description: 商家评分
        averPrice:
          type: integer
          format: int64
          description: 人均价格 单位为分
        tag:
          type: array
          items:
            type: string
            description: 商家标签
        info:
          type: string
          description: 商家优惠信息
        shopDetailsImgs:
          type: array
          description: 商家商店的描述信息图片
          items:
            type: string
        contactMobile:
          type: string
          description: 商家联系电话 用来联系商家用的
        shopAddress:
          type: object
          properties:
            address:
              type: string
              description: 商家地址字符串
            latitude:
              type: string
              description: "经度"
            longitude:
              type: string
              description: "纬度"

  requestBodies:
    ShopCreateOrEditReq:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ShopCreateModal'

